name: 'Hello World'
description: 'Greet someone and record the time'
author:'octocat@github.com'
inputs:
  description: 'Who to greet'
  required: true
  default: 'World'
runs:
  using: 'docker'
  main: 'Dockerfile'
branding:
  icon: 'mic'
  color: 'purple'
